name: Validate, Scan, and Tag Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for actions/checkout to fetch code
#  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
#  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  # Job 1: Format, Lint, Scan
  test-and-doc:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22

      # Required for terraform-docs to accurately map modules
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@37c3618610d60f92cc57cb7f7e74c2569db0fcd6
        with:
          terraform_version: "1.7.5"

      - name: Check Formatting
        run: terraform fmt -check

      - name: Initialize
        run: terraform init -backend=false

      - name: Validate Code
        run: terraform validate

      # TFLint 
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@bd0e7245fae11a8d34a7d8685532a3a56f6d1aeb

      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact
  
  #      # Checkov - Tuned for Azure 
  #      - name: Run Checkov Security Scan
  #        uses: bridgecrewio/checkov-action@4a1afa9897f7afe297a3762c926e1e800361464f
  #        with:
  #          framework: terraform
  #          output_format: cli
  #          soft_fail: false

  # Job 2: Auto-increment versions on merge
  tag-release:
    name: Auto-Tag Version
    needs: test-and-doc
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22
        with:
          fetch-depth: 0

      - name: Bump Version and Push Tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
